name: Node.js CI #Nombre del proceso que saldrá en la pestaña "Actions"

on: [push] #Disparador, se comprueba cada vez que se hace un push

jobs:
  build: #Nombre de este grupo de tareas
    runs-on: ubuntu-latest #Le dice a GitHub que alquile un ordenador virtual con Linux (Ubuntu) para ejecutar el código

    steps:
    - uses: actions/checkout@v4 #El robot "clona" el repositorio. Descarga el código desde GitHub a ese ordenador virtual para poder trabajar con él.
    
    - name: Use Node.js 20 #Instala la versión 20 de Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        
    - name: Install dependencies #Isnstala todas las librerías necesarias, incluyendo Express y NeDB
      run: npm install
        
    - name: Run server and tests
      run: | 
        npm start &  #Arranca servidor
        sleep 5 #Espera 5 segundos
        npm test #Lanza Newman y newman ejecuta los tests de Postman contra el servidor que acabas de arrancar